version: "3.1"

services:
  mariadb:
    image: mariadb:10.6.5-focal
    environment:
      - DATABASE=backend_coderhouse
      - PASSWORD=1234
      - USER=root
      - MARIADB_ROOT_PASSWORD=${PASS}
      - HOST=172.31.0.1
    ports:
      - 3306:3306
